using IVF.Domain.Common;

namespace IVF.Domain.Entities;

/// <summary>
/// Represents a CRL (Certificate Revocation List) generated by a CA.
/// Each CRL has a sequence number, validity period, and DER-encoded content.
/// Enterprise CAs generate CRLs periodically and on each revocation event.
/// </summary>
public class CertificateRevocationList : BaseEntity
{
    /// <summary>The CA that published this CRL.</summary>
    public Guid CaId { get; private set; }
    public CertificateAuthority Ca { get; private set; } = null!;

    /// <summary>Monotonically increasing CRL number (RFC 5280 §5.2.3).</summary>
    public long CrlNumber { get; private set; }

    /// <summary>thisUpdate — when this CRL was issued.</summary>
    public DateTime ThisUpdate { get; private set; }

    /// <summary>nextUpdate — when the next CRL is expected (clients cache until this time).</summary>
    public DateTime NextUpdate { get; private set; }

    /// <summary>PEM-encoded CRL for HTTP distribution.</summary>
    public string CrlPem { get; private set; } = null!;

    /// <summary>DER-encoded CRL bytes for binary distribution.</summary>
    public byte[] CrlDer { get; private set; } = null!;

    /// <summary>Number of revoked entries in this CRL.</summary>
    public int RevokedCount { get; private set; }

    /// <summary>SHA-256 hash of the CRL for integrity verification.</summary>
    public string Fingerprint { get; private set; } = null!;

    private CertificateRevocationList() { }

    public static CertificateRevocationList Create(
        Guid caId,
        long crlNumber,
        DateTime thisUpdate,
        DateTime nextUpdate,
        string crlPem,
        byte[] crlDer,
        int revokedCount,
        string fingerprint)
    {
        return new CertificateRevocationList
        {
            CaId = caId,
            CrlNumber = crlNumber,
            ThisUpdate = thisUpdate,
            NextUpdate = nextUpdate,
            CrlPem = crlPem,
            CrlDer = crlDer,
            RevokedCount = revokedCount,
            Fingerprint = fingerprint
        };
    }
}
