#!/bin/bash
set -e

# ─── Cloud Replica Initialization Script ────────────────────────────────────
# Runs on the REMOTE server when the cloud standby container first starts.
# Uses pg_basebackup over SSL to clone from the primary, then configures
# this instance as a streaming replication standby.
#
# Required env vars (set in .env or docker-compose environment section):
#   PRIMARY_HOST           — public IP / hostname of the primary server
#   PRIMARY_PORT           — primary PostgreSQL port (default: 5433)
#   REPLICATOR_USER        — replication username (default: replicator)
#   REPLICATOR_PASSWORD    — replication password
#   REPLICA_SLOT_NAME      — replication slot on primary (default: cloud_standby_slot)
#   REPLICA_APPLICATION    — application_name in primary_conninfo (default: ivf-cloud-replica)
#   PGSSLMODE              — SSL mode for replication (default: require)
# ─────────────────────────────────────────────────────────────────────────────

PGDATA="/var/lib/postgresql/data"

PRIMARY_HOST="${PRIMARY_HOST:?PRIMARY_HOST env var is required}"
PRIMARY_PORT="${PRIMARY_PORT:-5433}"
REPLICATOR_USER="${REPLICATOR_USER:-replicator}"
REPLICATOR_PASSWORD="${REPLICATOR_PASSWORD:?REPLICATOR_PASSWORD env var is required}"
REPLICA_SLOT_NAME="${REPLICA_SLOT_NAME:-cloud_standby_slot}"
REPLICA_APPLICATION="${REPLICA_APPLICATION:-ivf-cloud-replica}"
PGSSLMODE="${PGSSLMODE:-require}"

# ─── First-time initialization ────────────────────────────────────────────────
if [ -z "$(ls -A "$PGDATA" 2>/dev/null)" ]; then
    echo "Cloud Replica: PGDATA is empty — cloning from primary ($PRIMARY_HOST:$PRIMARY_PORT) over SSL ($PGSSLMODE)..."

    # Wait until the primary accepts connections
    until PGPASSWORD="$REPLICATOR_PASSWORD" \
        PGSSLMODE="$PGSSLMODE" \
        pg_isready -h "$PRIMARY_HOST" -p "$PRIMARY_PORT" -U "$REPLICATOR_USER" 2>/dev/null; do
        echo "  Waiting for primary at $PRIMARY_HOST:$PRIMARY_PORT ..."
        sleep 5
    done

    echo "Primary is ready. Starting pg_basebackup..."

    # ── Base backup over SSL ─────────────────────────────────────────────────
    PGPASSWORD="$REPLICATOR_PASSWORD" \
    PGSSLMODE="$PGSSLMODE" \
    pg_basebackup \
        -h "$PRIMARY_HOST" \
        -p "$PRIMARY_PORT" \
        -U "$REPLICATOR_USER" \
        -D "$PGDATA" \
        -Fp \
        -Xs \
        -P \
        --checkpoint=fast \
        --slot="$REPLICA_SLOT_NAME"

    # ── Signal file — marks this as a standby ────────────────────────────────
    touch "$PGDATA/standby.signal"

    # ── Replication connection config ────────────────────────────────────────
    cat >> "$PGDATA/postgresql.auto.conf" <<EOF

# ── Cloud streaming replication (auto-generated by cloud-replica-entrypoint.sh) ──
primary_conninfo = 'host=$PRIMARY_HOST port=$PRIMARY_PORT user=$REPLICATOR_USER password=$REPLICATOR_PASSWORD sslmode=$PGSSLMODE application_name=$REPLICA_APPLICATION'
primary_slot_name = '$REPLICA_SLOT_NAME'
hot_standby = on
recovery_min_apply_delay = 0
EOF

    echo "Cloud Replica: initialized successfully from primary ($PRIMARY_HOST:$PRIMARY_PORT)"

else
    echo "Cloud Replica: PGDATA already exists — starting as standby"

    # Ensure standby.signal is present (safeguard against accidental promotion)
    if [ ! -f "$PGDATA/standby.signal" ]; then
        echo "WARNING: standby.signal missing — recreating to prevent promotion"
        touch "$PGDATA/standby.signal"
    fi
fi

# Hand off to the standard PostgreSQL entrypoint
exec docker-entrypoint.sh postgres
