using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IVF.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddFormTemplateCode : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. Add nullable first to allow backfill
            migrationBuilder.AddColumn<string>(
                name: "Code",
                table: "form_templates",
                type: "character varying(50)",
                maxLength: 50,
                nullable: true);

            // 2. Backfill: use first 20 chars of UUID (hex, no hyphens) → guaranteed unique
            //    Real codes will be regenerated by FormTemplateCodeSeeder on app startup
            migrationBuilder.Sql(@"
                UPDATE form_templates
                SET ""Code"" = LEFT(REPLACE(""Id""::text, '-', ''), 20)
                WHERE ""Code"" IS NULL;
            ");

            // 3. Now enforce NOT NULL
            migrationBuilder.AlterColumn<string>(
                name: "Code",
                table: "form_templates",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                defaultValue: "form",
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldNullable: true);

            // 4. Unique index (partial: only non-deleted rows)
            migrationBuilder.CreateIndex(
                name: "IX_form_templates_code",
                table: "form_templates",
                column: "Code",
                unique: true,
                filter: "\"IsDeleted\" = false");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_form_templates_code",
                table: "form_templates");

            migrationBuilder.DropColumn(
                name: "Code",
                table: "form_templates");
        }
    }
}
